### ISSUE TITLE
Seems key is inserted before refresh sometimes

### ISSUE THREAD

**Issue by daiheitan** [jonhoo/rust-evmap#1]
Using evmap in a high concurrency situation. I use `contains_key` to check if the evmap already contains the data and read it, if not, insert something and call `refresh`. But sometimes it seems that a `contains_key` check could happen between adding the key and inserting the value during a `refresh`. This makes `contains_key` returning true and `get_and` fails with `None`

(Yeah the issue title is not quite accurate)

**Comment by jonhoo** [comment]
Hmm.. Are you calling `contains_key` on a `WriteHandle` or on a `ReadHandle`? Does this happen before or after the first time you call `refresh()`? I'm very surprised to hear about this behavior, as `contains_key` follows almost exactly the same code path as `get_and`...

**Comment by daiheitan** [comment]
calling `contains_key` on a ReadHandle.

I viewed the source code, and here's my hypothesis:

When I call `.insert()` on a `WriteHandle`, a new key is inserted to `inner`, but it is not maked ready. `ReadHandle::contains_key` do not run a ready check, so it could see the key and return true. But since `WriteHandle::refresh()` is not yet executed, `get_and` returns `None`.

**Comment by jonhoo** [comment]
`ReadHandle` should not see the key in the map at all until after a `refresh()` because the `.insert()` is acting on an entirely separate map. The initial map used by `ReadHandle` is completely empty, and so `contains_key` should *always* return `false` until the first `refresh()`. On `refresh()`, the map is marked as ready, so `get_and` and `contains_key` should do the same thing.

Are you sure you're never accessing `WriteHandle` from multiple threads at a time? And that you have *never* called `refresh()` when observing this behavior?
