### ISSUE TITLE
`write::with_mut`'s unwrap call could panic

### ISSUE THREAD

**Issue by daiheitan** [jonhoo/rust-evmap#2]
att

**Comment by jonhoo** [comment]
No, this should not be the case. The only time `w_handle` is `None` is *during* a `refresh`. Since `refresh` mutably borrows the `WriteHandle`, and does not call `with_mut`, the latter can not be executed at that time, and so should never see it be `None`. Have you actually seen this happen? If so, that's definitely a bug.

**Comment by daiheitan** [comment]
I found this bug along with the another issue I filed. Though currently I have no time to figure out the exactly reason of the unwrap panic, I could say the panic appears after running multi-threads under heavy pressure for a period of time (I was running pressure test under 3 min)

**Comment by daiheitan** [comment]
I'm using the evmap in a global static ref. So I have to use *const -> *mut pointer conversion to get a mutable ref of WriteHandle. Could that be the problem?

```rust
ReadHandle::get_and(|v| {
  // do something
}).unwrap_or_else(|| {
  let w = &w_handle as *const WriteHandle;
  let w = w as *mut WriteHandle;
  // unsafe write & refresh
})
```

**Comment by jonhoo** [comment]
Well, `WriteHandle` is not safe to use from multiple threads at the same time. Does this code appear in multiple places, or within code executed by multiple threads?

**Comment by daiheitan** [comment]
I am not following. Isn't a concurrent hashmap meant to support multi-thread writing?

**Comment by jonhoo** [comment]
Ah, no, this map provides concurrency between *reads* and writes, not between multiple writers. The Rust type system should have warned you about this: `WriteHandle::insert` takes an `&mut self`, and `WriteHandle` is not `Clone`, nor can you generate a second one. However, you masked this by doing the unsafe transmute that essentially creates multiple mutable pointers to the same `WriteHandle`. That would definitely break everything, and is one of the reasons you need to be *very* careful with `unsafe` code.

I don't know that this library will ever provide support for concurrent writers. It's goal is to provide high throughput *reads* in the presence of writes. You can address the use-case you are after by wrapping the `WriteHandle` in an `Arc<Mutex<>>`, and then using `arc.lock().unwrap().insert()`. The performance of this will still be decent assuming that reads are relatively much more frequent than writes.

**Comment by daiheitan** [comment]
I see. This makes the performance comparation with `chashmap` somehow unfair. As `chashmap` supports multiple writers. I will close these issues. Thanks for your quick reply.

**Comment by jonhoo** [comment]
The comparison shown in the `README` is using the solution I gave above (wrapping the `WriteHandle` in `Arc<Mutex<>>), which *does* allow multiple writers (they will just take a lock). The numbers in that scenario are in fact comparable, since they provide similar interfaces (i.e., multiple concurrent readers and writers).

**Comment by daiheitan** [comment]
Got. Thanks 😃
