### ISSUE TITLE
Float as value

### ISSUE THREAD

**Issue by AttilaOrs** [jonhoo/rust-evmap#26]
Hi,
I'm trying to use evmap with float values, like this:
```   
let (read_handler, mut write_handler ) = evmap::new();
write_handler.insert("my key", 0.12 as f32);
```
However, I've got two errors: 
-  the trait `std::cmp::Eq` is not implemented for `f32`
-  the trait `evmap::shallow_copy::ShallowCopy` is not implemented for `f32`

As I'm guessing the main reason is that float does not implement f32 (and that's why evmap did not implement ShallowCopy), but still I think is a valid use case. 

I am also not sure how to implement ShallowCopy for my own structure. Putting it in a Box solves the problem, but I don't see why I would need a box.  I think it would be usefull to put in the documentation an example for something like this:
```
#[derive(PartialEq, Eq, Hash)]
struct MyStruct(i32);
```
Thank you for you help.

**Comment by jonhoo** [comment]
That's an interesting observation, thank you! You are right that this is a combination of the requirements for `ShallowCopy` and `Eq`. It was an oversight that `f32` did not implement that trait (all `Copy` types trivially implement `ShallowCopy`), and I've rectified that in 5.0.1. I also added some better docs for how to implement it yourself :)

As for `Eq`, that's harder to do much about for `f32`; you'll probably need your own newtype wrapper as you observe. `Eq` is only required for the value type for the `remove` operation, but I think it'd probably be a mistake to remove that. _Technically_ you can achieve the same thing with just `retain`, but it's a bit slower and more tedious to use. I also don't see a good way to provide `remove` only when the value type is `Eq` due to the operational log that evmap must maintain. If anyone has a good idea there though, I'm all ears!

**Comment by AttilaOrs** [comment]
Thank you for the fast response.
My best ques is to restrict those operations (mainly `remove` I guess) for types which do not implement `Eq`.  However, I am far from an expert.
Thank you again.
