### ISSUE TITLE
Where is .keys() method of underlying HashMap?

### ISSUE THREAD

**Issue by serzhiio** [jonhoo/rust-evmap#27]
subj

**Comment by novacrazy** [comment]
There isn't one, at least not directly. You can use [`ReadHandle::for_each`](https://docs.rs/evmap/5.0.2/evmap/struct.ReadHandle.html#method.for_each) to iterate through all keys and optionally the values as well.

However, due to the nature of reading the shared maps, if any substantial computation is done while scanning the keys, this will block `WriteHandle`s from refreshing. I'd suggest quickly finding the key/value you need, cloning the key/value and then using it outside after the `for_each` call.

**Comment by serzhiio** [comment]
My knowledge is not deep enough, but isnt it cheap to get just Vec of Keys
at once?

пт, 10 мая 2019 г., 2:48 Aaron Trent <notifications@github.com>:

**Comment by novacrazy** [comment]
No. 

The underlying hashmaps don't usually store the keys in contiguous memory, and `.keys()` for the standard library `HashMap` and `hashbrown` both return a lazily evaluated iterator rather than a `Vec`.
