### ISSUE TITLE
How to update values without copying

### ISSUE THREAD

**Issue by kolemannix** [jonhoo/rust-evmap#29]
Thanks for this great crate!

Is there a way to work with values inside an `evmap` mutably? I am storing larger records inside an evmap and would like the ability to update them without making copies. Something like `get_and`, but with a `FnMut`? The desire is for something akin to the Entry API that allows fetching and updating a value with a single operation.

As I understand it, this is a bit more complex since this is a multivalued map, and every operation must be encoded as, well, an `Operation`. But perhaps it could be done by index, for instance
```rust
let result: Option<()> = rh.get_and_update(&key, idx, |elem| elem += 1)
```
where, similarly to `get_and`, `None` is returned if the key or index didn't lead to an element.

If I'm understanding `Operation` correctly, perhaps this could be encoded as
`Update(K, Index, NewV)`, or simply as a `Remove` followed by an `Add`.

If this sounds at all like a reasonable or possible thing to add, I would be happy to try and help with implementation. Thanks again!

**Comment by jonhoo** [comment]
The issue here is that the elements are actually _aliased_ between the two maps, they are not copied. This means that you'd be modifying the elements while they are also being accessed by readers, which probably isn't safe.

What we might be able to do is something like:
```rust
fn read_copy_update<F>(&mut self, key: K, f: F)
  where F: FnMut(usize, &V) -> V
```
Where it'll call the closure for each element of the value set for `key`, and substitute out all the values with the given replacement in a safe manner. I don't know if the ability to read the existing value would help you much though?

**Comment by kolemannix** [comment]
If by "the ability to read the existing value", you mean the fact that the closure receives an `&mut V` to work with, yes it is important. But getting the updated value out (i.e., the return value of `read_copy_update`) is not needed for my use case.

I think a method like this would work well overall. Though I'm almost always targeting a particular element so it could be a bit wasteful to have the closure no-op for all but one element, but mine is just one use-case.

**Comment by jonhoo** [comment]
Ah, no, I explicitly meant _read_ (as in `&V`). evmap cannot give you `&mut V`, since the `V`s are aliased between the two maps, so readers may be accessing them concurrently with the writer. It would be a race condition to allow you to mutate the elements while readers still have access to them. This is why you'd need a pattern like `read_copy_update` above, where you are given a `&V` and return a new value `V`.

**Comment by kolemannix** [comment]
Ah, understood. Of course.

The issue then for me would be the cost of the copy.

Thanks for you help. I was under the impression the read and write maps contained clones, not aliases. It doesn't sound like the type of mutable access I want is a good fit for `evmap`.

**Comment by jonhoo** [comment]
Yeah, it's sort of a fundamental trade-off where either you have to incur twice the memory cost by keeping two copies, or you give up the ability to keep distinct variants (and thus mutability) by aliasing. evmap chooses the latter, and I think it'd be hard to retrofit it to allow the other mode of operation. It _might_ be possible, though we might need the specialization feature for that.

**Comment by jonhoo** [comment]
I'll close this, as mutable access to the elements would require duplicating all the values. Maaybe there's some funky scheme where you only duplicate when you have to modify, but that is far beyond what evmap can currently do. Would be happy to take a look at a proposal though!
