### ISSUE TITLE
evmaps cannot be used in `lazy_static`?

### ISSUE THREAD

**Issue by vext01** [jonhoo/rust-evmap#5]
Hi,

I was wondering if it is possible to use an evmap in a `lazy_static!` block.

See this Stack Overflow question for details about the error message you will get if you try:
https://stackoverflow.com/questions/47818811/can-i-use-an-evmap-inside-a-lazy-static/47818987#47818987

Thanks

**Comment by jonhoo** [comment]
Hi there!

As the answer on your SO question points out, evmap does not allow you to take a single `ReadHandle` and share it among threads. And this is intentional. Part of the way evmap achieves its concurrency is by keeping some local state with each reader; this means that even though each `ReadHandle` method takes an `&self`, it is *actually* modifying its internal state behind the scenes (which is only safe within the confines of a single thread).

The way to achieve what you are after is to keep a global `Mutex<ReadHandle>`, and to have each thread that wants to read clone that `ReadHandle` on its first read, and then re-use that same handle on subsequent reads. You should also think about whether you *really* want to use a static here -- statics are shared across all threads of your program, including tests, which means that you probably won't be able to run your tests in parallel (or even sequentially without cleanup).
