### ISSUE TITLE
Possible to shallowcopy a HashMap

### ISSUE THREAD

**Issue by longbinlai** [jonhoo/rust-evmap#55]
Thank you for this work. We are recently in using evmap in our DB system as the caching module, but we find out a case that need to use a HashMap as the Value. However, according to the trait bound, the HashMap needs to be `ShallowCopiable`, which is not yet implemented in the codebase. Is it possible to make it so? Thank you.

**Comment by jonhoo** [comment]
Huh, that is an interesting question... I'm guessing you mean `ReadHandle` specifically? Since `ReadHandle` isn't `Sync`, I doubt you'd be able to use it much even if it implemented `ShallowCopy`.

Or are you referring to the standard library `HashMap`? For that one, I think we probably could implement `ShallowCopy`, although it'll probably be a little involved since it has a more complex inner structure. It should "just work" if you have a `Box<HashMap>` instead though?
