### ISSUE TITLE
Replace Clone bound with Freeze

### ISSUE THREAD

**Issue by jfcha** [jonhoo/rust-evmap#71]
There is currently an [RFC](https://github.com/rust-lang/rfcs/pull/2944#issuecomment-714795928) being considered for the Freeze trait. I believe that targeting this trait could simplify evmap's implementation (likely removing ShallowCopy) and expanding its bounds (it's an auto trait for all structs not directly containing UnsafeCell). The current belief is that there are only niche use cases for this trait and not worth adding to the standard library, but it would be great to hear if a more well known crate like evmap could benefit from it's addition.

**Comment by jonhoo** [comment]
Hmm, I don't see how `Freeze` removes the need for `ShallowCopy`? Just because a type has no interior mutability does not mean it can be cheaply aliased the way `ShallowCopy` enables.

**Comment by jfcha** [comment]
Hmm. I think it does so long as you keep track of the number of aliases that exist? If I'm wrong I'd love to have a counter example.

The general idea is if something is immutable, you can't tell the difference whether you're viewing a copy from location A or a copy from location B (self-referential structs excluded and not safe in Rust anyway). In Rust you can tell that there are two copies of non-copy things because drop is called by each. However, if you take on the responsibility of calling drop by ManuallyDrop on insert, you can have multiple copies of an immutable item and your users would never know the difference.  You can create copies of the immutable bytes with the very fast ptr::copy_nonoverlapping and when the last copy is about to go out of scope, you call ptr::drop_in_place on it.

Besides managing the drops, the Freeze bound is the necessary enabler for this type of scheme because if T has a Mutex or any interior mutability, you will never know when it is actually safe to copy the bytes. There may be other caveats that I'm not thinking of (like can you copy_nonoverlapping a MaybeUninit?), but the working theory is

Manual dropping + Reference counting + Freeze  =  Very cheap aliasing
 
So instead of the Copy, ShallowCopy, Clone dance, you would: have a Freeze bound, use copy_nonoverlapping between maps, and manually call drop on the items that have been replaced when you switch over the readers.

If Freeze was an auto trait, you would also have a significantly wider scope of compatible structs than you'll get with either Copy or Clone and they would all have equally cheap copying cost.

Hopefully this makes sense, and I don't actually expect you to pursue this because even in theory it's only a marginal gain, but I thought it may be worth considering in light of the RFC.

**Comment by jonhoo** [comment]
Actually, thinking some more about it, I wonder if the concern is the other way around: there may be types that _do_ have interior mutability that users nevertheless want to implement `ShallowCopy` for, because they know they never modify that value when it is present in the map.

That said, I think your argument is probably sound that `Freeze` would go a long way towards what `ShallowCopy` is trying to capture. It's a little weird though, because `ShallowCopy` isn't _really_ about interior mutability — it was originally intended as a way to indicate that an alias copy of type can be cheaply constructed. I feel like even though `Freeze` probably implies `ShallowCopy` (or close to it), they're different enough in semantics that I think I'd want them to be separate. As mentioned above, it might be that a user wants to `ShallowCopy` a value that isn't `Freeze` (and it's on them to not invoke the interior mutability). I don't know if I can think of the opposite case — where someone wants a type to be `Freeze` but _not_ `ShallowCopy` — but the fact that it isn't clear makes me think that these really are distinct types with (subtly) different meanings.

**Comment by jfcha** [comment]
Yeah. You're right. Freeze would at best be a subset, and theoretically you shouldn't have to disallow InteriorMutability in the types. In an ideal world you could do something like only give out &immut references which could be used anywhere & was used, but then error or warn if there was attempt to write to an UnsafeCell. Then you could still safely do the cheap ptr::copy, ManuallyDrop trick and you wouldn't have the limits on the types. Unfortunately, I don't think something like &immut is coming anytime soon. Anyway, I've been thinking about Freeze for my own projects and I thought I'd point it out as a potentially interesting alternative approach for evmap. I'm going to close this, but thanks for your time and thoughts! Cheers!
